server:
  port: 8080


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: ms-producto
          uri: lb://ms-producto
          predicates:
            - Path=/productos/**
        - id: ms_catalogo
          uri: lb://ms_catalogo
          predicates:
            - Path=/categorias/**