
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true


      routes:
        - id: ms-producto-service
          uri: lb://ms-producto-service
          predicates:
            - Path=/productos/**

