
server:
  port: 8085

spring:
  cloud:
    gateway:

      routes:
        - id: ms-catalogo-service
          uri: lb://ms-catalogo-service
          predicates:
            - Path=/categorias/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
